# Generated by Django 4.0.4 on 2022-06-18 09:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='نام مقاله')),
                ('description', models.CharField(default=None, max_length=30, verbose_name='توضیحات')),
                ('content', models.TextField(default=None, verbose_name='محتوا')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 6, 18, 9, 43, 49, 728770, tzinfo=utc), verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(default=None, upload_to='blog/', verbose_name='تصویر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
    ]
