# Generated by Django 4.0.4 on 2022-06-19 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(verbose_name='نامک')),
                ('date', models.DateTimeField(verbose_name='تاریخ انتشار')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default=None, max_length=100, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.category', verbose_name='دسته بندی'),
        ),
    ]
