# Generated by Django 4.0.4 on 2022-06-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_blog_description_alter_blog_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='نام تگ')),
                ('slug', models.SlugField(verbose_name='نامک')),
                ('date', models.DateTimeField(verbose_name='تاریخ انتشار')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(related_name='blogs', to='blog.tag', verbose_name='تگ'),
        ),
    ]
