# Generated by Django 4.0.4 on 2022-06-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_blog_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام ')),
                ('email', models.EmailField(default='mail@gmail.com', max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='نظر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='blog.blog', verbose_name='بلاگ')),
            ],
        ),
    ]
