# Generated by Django 4.0.4 on 2022-06-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_date_alter_tag_date_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category_name',
            new_name='category',
        ),
    ]
