# Generated by Django 4.0.4 on 2022-06-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='نام')),
                ('email', models.EmailField(default='mail@gmail.com', max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.IntegerField(default=None, max_length=11, verbose_name='شماره تماس')),
                ('number', models.IntegerField(default=None, verbose_name='تعداد')),
                ('time', models.IntegerField(default=None, verbose_name='زمان رزرو')),
                ('pub_date', models.DateTimeField(default=None, verbose_name='تاریخ رزرو')),
            ],
        ),
    ]
