# Generated by Django 4.0.4 on 2022-06-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='pub_date',
            new_name='date',
        ),
    ]
