# Generated by Django 4.0.4 on 2022-06-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_pub_date_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=None, verbose_name='تاریخ رزرو'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default=None, max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=None, verbose_name='زمان رزرو'),
        ),
    ]
