# Generated by Django 4.0.4 on 2022-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(default=None, upload_to='foods/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=None, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='food',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='food',
            name='rate',
            field=models.IntegerField(default=None, verbose_name='امتیاز'),
        ),
        migrations.AddField(
            model_name='food',
            name='time',
            field=models.IntegerField(default=None, verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(default=None, max_length=30, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
