# Generated by Django 4.0.4 on 2022-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_photo_food_price_food_pub_date_food_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='foodtype',
            field=models.CharField(choices=[('cake', 'کیک'), ('lunch', 'ناهار'), ('coffee', 'قهوه'), ('drink', 'نوشیدنی سرد')], default='drink', max_length=10, verbose_name='نوع سفارش'),
        ),
    ]
